/** Where the desi diaspora actually lists from — the rest is free text. */
export const COUNTRIES = [
  "USA",
  "India",
  "Canada",
  "United Kingdom",
  "Australia",
  "New Zealand",
  "UAE",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Oman",
  "Bahrain",
  "Singapore",
  "Malaysia",
  "Nepal",
  "Pakistan",
  "Bangladesh",
  "Sri Lanka",
  "South Africa",
  "Kenya",
  "Ireland",
  "Germany",
  "Netherlands",
  "Japan",
  "Fiji",
  "Trinidad & Tobago",
  "Guyana",
  "Mauritius",
] as const;
