ALTER TABLE "User"
  ADD COLUMN "headline" TEXT,
  ADD COLUMN "lookingFor" TEXT,
  ADD COLUMN "education" TEXT,
  ADD COLUMN "experience" TEXT,
  ADD COLUMN "skills" TEXT[] DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "languages" TEXT[] DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "videoUrls" TEXT[] DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "openToWork" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "websiteUrl" TEXT,
  ADD COLUMN "instagramUrl" TEXT,
  ADD COLUMN "facebookUrl" TEXT,
  ADD COLUMN "youtubeUrl" TEXT,
  ADD COLUMN "linkedinUrl" TEXT,
  ADD COLUMN "xUrl" TEXT,
  ADD COLUMN "tiktokUrl" TEXT,
  ADD COLUMN "threadsUrl" TEXT,
  ADD COLUMN "telegramUrl" TEXT,
  ADD COLUMN "pinterestUrl" TEXT,
  ADD COLUMN "snapchatUrl" TEXT,
  ADD COLUMN "githubUrl" TEXT,
  ADD COLUMN "whatsappNumber" TEXT;
